### ISSUE TITLE
colord error

### ISSUE THREAD

**Issue by Skaendo** [CinnamonSlackBuilds/csb#21] opened 2017-06-30 05:07 UTC
### Slackware Version
-current
### GIT Branch
master
### Description
Now I'm stuck at colord erroring out on me, normal fresh full current installation, and when the build script gets to colord it errors out. My full log is here: https://pastebin.com/kzku3guZ, and the last few lines look like this:

/usr/include/glib-2.0/glib/gmacros.h:444:22: note: in expansion of macro ‘_GLIB_AUTOPTR_FUNC_NAME’
   static inline void _GLIB_AUTOPTR_FUNC_NAME(TypeName) (TypeName **_ptr) { if (*_ptr) (func) (*_ptr); }         \
                      ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/polkit-1/polkit/polkittypes.h:68:1: note: in expansion of macro ‘G_DEFINE_AUTOPTR_CLEANUP_FUNC’
 G_DEFINE_AUTOPTR_CLEANUP_FUNC (PolkitAuthority, g_object_unref)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[4]: *** [Makefile:1134: colord-cd-common.o] Error 1
make[4]: Leaving directory '/tmp/csb/colord-1.3.5/src'
make[3]: *** [Makefile:1377: all-recursive] Error 1
make[3]: Leaving directory '/tmp/csb/colord-1.3.5/src'
make[2]: *** [Makefile:825: all] Error 2
make[2]: Leaving directory '/tmp/csb/colord-1.3.5/src'
make[1]: *** [Makefile:579: all-recursive] Error 1
make[1]: Leaving directory '/tmp/csb/colord-1.3.5'
make: *** [Makefile:511: all] Error 2

I am stumped with this one. This is only happening on current for me as far as I can tell.

**Comment by Skaendo** [comment] 2017-06-30 05:22
I'm guessing that this is a more relevant part:

/usr/include/glib-2.0/glib/gmacros.h:430:43: error: redefinition of ‘glib_autoptr_cleanup_PolkitAuthorizationResult’
 #define _GLIB_AUTOPTR_FUNC_NAME(TypeName) glib_autoptr_cleanup_##TypeName

Maybe something to do with polkit?

**Comment by willysr** [comment] 2017-06-30 06:17
yes, it's only in current since i didn't bump in 14.2 branch
i can reproduce the build failure, but no solutions at this moment. 

i will do some digging and see if i can find the fix.

thanks for reporting

**Comment by Skaendo** [comment] 2017-06-30 07:33
I've actually bumped colord to 1.3.5 in my projects 14.2 branch and it builds fine for me on 14.2 (I'm using slackrepo there). I'm pretty sure that I haven't bumped any other packages that you didn't from 14.2 to current, like mozjs I still have at 24.2.0, cjs I still have at 3.2.0, etc.

**Comment by willysr** [comment] 2017-06-30 08:03
14.2 still using the old mozjs and cjs
i only push the new cjs and mozjs in master branch

anyway, i raised an issue upstream: https://github.com/hughsie/colord/issues/40

**Comment by Skaendo** [comment] 2017-06-30 08:59
Yep.
Did you see this issue?: https://github.com/hughsie/colord/issues/36

**Comment by willysr** [comment] 2017-06-30 09:00
Yes, but that should be solved already and it looks a little bit different with what we had here

**Comment by willysr** [comment] 2017-06-30 10:47
@Skaendo : ok, it's fixed in git master :)

**Closed** 2017-06-30 10:46 UTC
Labels: bug

**Comment by Skaendo** [comment] 2017-06-30 15:05
Thanks Willy
